#Victimhood is nice starts like this   Victimhood, I heed the call To step out of victimhood// kimi, nimine russell, krupfe, nimine, nimeli, haptic unt unt gussell, nimine rui rui gussell krupfe haptic rui russell russell misto misto krupfe unt smack krupfe rui koun unt rush krupfe unt smack  kimi, nimine russell, krupfe, nimine, nimeli, haptic unt unt gussell
#NATO encoding would be more simple// vihtctsoov.
#tool encoding  is// cancer-sign ra ta ca ra....
#Playing little games...
#How much wood could a woodchuck chuck if a woodchuck could chuck wood???...or else τι κάνει νιάου νιάου στα κεραμμύδια?
